"""A dictionary reference based on ISO Alpha3 Country Code"""

COUNTRY_REFERENCE = {
    "ABW": {
        "continent": "North America",
        "country_name": "Aruba",
        "region": "Caribbean",
    },
    "AFG": {
        "continent": "Asia",
        "country_name": "Afghanistan",
        "region": "Southern Asia",
    },
    "AGO": {"continent": "Africa", "country_name": "Angola", "region": "Middle Africa"},
    "AIA": {
        "continent": "North America",
        "country_name": "Anguilla",
        "region": "Caribbean",
    },
    "ALA": {
        "continent": "Europe",
        "country_name": "Åland Islands",
        "region": "Northern Europe",
    },
    "ALB": {
        "continent": "Europe",
        "country_name": "Albania",
        "region": "Southern Europe",
    },
    "AND": {
        "continent": "Europe",
        "country_name": "Andorra",
        "region": "Southern Europe",
    },
    "ARE": {
        "continent": "Asia",
        "country_name": "United Arab Emirates",
        "region": "Western Asia",
    },
    "ARG": {
        "continent": "South America",
        "country_name": "Argentina",
        "region": "South America",
    },
    "ARM": {"continent": "Asia", "country_name": "Armenia", "region": "Western Asia"},
    "ASM": {
        "continent": "Oceania",
        "country_name": "American Samoa",
        "region": "Polynesia",
    },
    "ATA": {
        "continent": "Antarctica",
        "country_name": "Antarctica",
        "region": "Antarctica",
    },
    "ATF": {
        "continent": "Africa",
        "country_name": "French Southern Territories",
        "region": "Eastern Africa",
    },
    "ATG": {
        "continent": "North America",
        "country_name": "Antigua and Barbuda",
        "region": "Caribbean",
    },
    "AUS": {
        "continent": "Oceania",
        "country_name": "Australia",
        "region": "Australia and New Zealand",
    },
    "AUT": {
        "continent": "Europe",
        "country_name": "Austria",
        "region": "Western Europe",
    },
    "AZE": {
        "continent": "Asia",
        "country_name": "Azerbaijan",
        "region": "Western Asia",
    },
    "BDI": {
        "continent": "Africa",
        "country_name": "Burundi",
        "region": "Eastern Africa",
    },
    "BEL": {
        "continent": "Europe",
        "country_name": "Belgium",
        "region": "Western Europe",
    },
    "BEN": {"continent": "Africa", "country_name": "Benin", "region": "Western Africa"},
    "BES": {
        "continent": "North America",
        "country_name": "Bonaire, Sint Eustatius and Saba",
        "region": "Caribbean",
    },
    "BFA": {
        "continent": "Africa",
        "country_name": "Burkina Faso",
        "region": "Western Africa",
    },
    "BGD": {
        "continent": "Asia",
        "country_name": "Bangladesh",
        "region": "Southern Asia",
    },
    "BGR": {
        "continent": "Europe",
        "country_name": "Bulgaria",
        "region": "Eastern Europe",
    },
    "BHR": {"continent": "Asia", "country_name": "Bahrain", "region": "Western Asia"},
    "BHS": {
        "continent": "North America",
        "country_name": "Bahamas",
        "region": "Caribbean",
    },
    "BIH": {
        "continent": "Europe",
        "country_name": "Bosnia and Herzegovina",
        "region": "Southern Europe",
    },
    "BLM": {
        "continent": "North America",
        "country_name": "Saint Barthélemy",
        "region": "Caribbean",
    },
    "BLR": {
        "continent": "Europe",
        "country_name": "Belarus",
        "region": "Eastern Europe",
    },
    "BLZ": {
        "continent": "North America",
        "country_name": "Belize",
        "region": "Central America",
    },
    "BMU": {
        "continent": "North America",
        "country_name": "Bermuda",
        "region": "Northern America",
    },
    "BOL": {
        "continent": "South America",
        "country_name": "Bolivia",
        "region": "South America",
    },
    "BRA": {
        "continent": "South America",
        "country_name": "Brazil",
        "region": "South America",
    },
    "BRB": {
        "continent": "North America",
        "country_name": "Barbados",
        "region": "Caribbean",
    },
    "BRN": {
        "continent": "Asia",
        "country_name": "Brunei Darussalam",
        "region": "South-eastern Asia",
    },
    "BTN": {"continent": "Asia", "country_name": "Bhutan", "region": "Southern Asia"},
    "BVT": {
        "continent": "South America",
        "country_name": "Bouvet Island",
        "region": "South America",
    },
    "BWA": {
        "continent": "Africa",
        "country_name": "Botswana",
        "region": "Southern Africa",
    },
    "CAF": {
        "continent": "Africa",
        "country_name": "Central African Republic",
        "region": "Middle Africa",
    },
    "CAN": {
        "continent": "North America",
        "country_name": "Canada",
        "region": "Northern America",
    },
    "CCK": {
        "continent": "Oceania",
        "country_name": "Cocos (Keeling) Islands",
        "region": "Australia and New Zealand",
    },
    "CHE": {
        "continent": "Europe",
        "country_name": "Switzerland",
        "region": "Western Europe",
    },
    "CHL": {
        "continent": "South America",
        "country_name": "Chile",
        "region": "South America",
    },
    "CHN": {"continent": "Asia", "country_name": "China", "region": "Eastern Asia"},
    "CIV": {
        "continent": "Africa",
        "country_name": "Côte d’Ivoire",
        "region": "Western Africa",
    },
    "CMR": {
        "continent": "Africa",
        "country_name": "Cameroon",
        "region": "Middle Africa",
    },
    "COD": {
        "continent": "Africa",
        "country_name": "Democratic Republic of the Congo",
        "region": "Middle Africa",
    },
    "COG": {"continent": "Africa", "country_name": "Congo", "region": "Middle Africa"},
    "COK": {
        "continent": "Oceania",
        "country_name": "Cook Islands",
        "region": "Polynesia",
    },
    "COL": {
        "continent": "South America",
        "country_name": "Colombia",
        "region": "South America",
    },
    "COM": {
        "continent": "Africa",
        "country_name": "Comoros",
        "region": "Eastern Africa",
    },
    "CPV": {
        "continent": "Africa",
        "country_name": "Cabo Verde",
        "region": "Western Africa",
    },
    "CRI": {
        "continent": "North America",
        "country_name": "Costa Rica",
        "region": "Central America",
    },
    "CUB": {
        "continent": "North America",
        "country_name": "Cuba",
        "region": "Caribbean",
    },
    "CUW": {
        "continent": "North America",
        "country_name": "Curaçao",
        "region": "Caribbean",
    },
    "CXR": {
        "continent": "Oceania",
        "country_name": "Christmas Island",
        "region": "Australia and New Zealand",
    },
    "CYM": {
        "continent": "North America",
        "country_name": "Cayman Islands",
        "region": "Caribbean",
    },
    "CYP": {"continent": "Asia", "country_name": "Cyprus", "region": "Western Asia"},
    "CZE": {
        "continent": "Europe",
        "country_name": "Czechia",
        "region": "Eastern Europe",
    },
    "DEU": {
        "continent": "Europe",
        "country_name": "Germany",
        "region": "Western Europe",
    },
    "DJI": {
        "continent": "Africa",
        "country_name": "Djibouti",
        "region": "Eastern Africa",
    },
    "DMA": {
        "continent": "North America",
        "country_name": "Dominica",
        "region": "Caribbean",
    },
    "DNK": {
        "continent": "Europe",
        "country_name": "Denmark",
        "region": "Northern Europe",
    },
    "DOM": {
        "continent": "North America",
        "country_name": "Dominican Republic",
        "region": "Caribbean",
    },
    "DZA": {
        "continent": "Africa",
        "country_name": "Algeria",
        "region": "Northern Africa",
    },
    "ECU": {
        "continent": "South America",
        "country_name": "Ecuador",
        "region": "South America",
    },
    "EGY": {
        "continent": "Africa",
        "country_name": "Egypt",
        "region": "Northern Africa",
    },
    "ERI": {
        "continent": "Africa",
        "country_name": "Eritrea",
        "region": "Eastern Africa",
    },
    "ESH": {
        "continent": "Africa",
        "country_name": "Western Sahara",
        "region": "Northern Africa",
    },
    "ESP": {
        "continent": "Europe",
        "country_name": "Spain",
        "region": "Southern Europe",
    },
    "EST": {
        "continent": "Europe",
        "country_name": "Estonia",
        "region": "Northern Europe",
    },
    "ETH": {
        "continent": "Africa",
        "country_name": "Ethiopia",
        "region": "Eastern Africa",
    },
    "FIN": {
        "continent": "Europe",
        "country_name": "Finland",
        "region": "Northern Europe",
    },
    "FJI": {"continent": "Oceania", "country_name": "Fiji", "region": "Melanesia"},
    "FLK": {
        "continent": "South America",
        "country_name": "Falkland Islands ",
        "region": "South America",
    },
    "FRA": {
        "continent": "Europe",
        "country_name": "France",
        "region": "Western Europe",
    },
    "FRO": {
        "continent": "Europe",
        "country_name": "Faroe Islands",
        "region": "Northern Europe",
    },
    "FSM": {
        "continent": "Oceania",
        "country_name": "Micronesia ",
        "region": "Micronesia",
    },
    "GAB": {"continent": "Africa", "country_name": "Gabon", "region": "Middle Africa"},
    "GBR": {
        "continent": "Europe",
        "country_name": "United Kingdom of Great Britain and Northern Ireland",
        "region": "Northern Europe",
    },
    "GEO": {"continent": "Asia", "country_name": "Georgia", "region": "Western Asia"},
    "GGY": {
        "continent": "Europe",
        "country_name": "Guernsey",
        "region": "Northern Europe",
    },
    "GHA": {"continent": "Africa", "country_name": "Ghana", "region": "Western Africa"},
    "GIB": {
        "continent": "Europe",
        "country_name": "Gibraltar",
        "region": "Southern Europe",
    },
    "GIN": {
        "continent": "Africa",
        "country_name": "Guinea",
        "region": "Western Africa",
    },
    "GLP": {
        "continent": "North America",
        "country_name": "Guadeloupe",
        "region": "Caribbean",
    },
    "GMB": {
        "continent": "Africa",
        "country_name": "Gambia",
        "region": "Western Africa",
    },
    "GNB": {
        "continent": "Africa",
        "country_name": "Guinea-Bissau",
        "region": "Western Africa",
    },
    "GNQ": {
        "continent": "Africa",
        "country_name": "Equatorial Guinea",
        "region": "Middle Africa",
    },
    "GRC": {
        "continent": "Europe",
        "country_name": "Greece",
        "region": "Southern Europe",
    },
    "GRD": {
        "continent": "North America",
        "country_name": "Grenada",
        "region": "Caribbean",
    },
    "GRL": {
        "continent": "North America",
        "country_name": "Greenland",
        "region": "Northern America",
    },
    "GTM": {
        "continent": "North America",
        "country_name": "Guatemala",
        "region": "Central America",
    },
    "GUF": {
        "continent": "South America",
        "country_name": "French Guiana",
        "region": "South America",
    },
    "GUM": {"continent": "Oceania", "country_name": "Guam", "region": "Micronesia"},
    "GUY": {
        "continent": "South America",
        "country_name": "Guyana",
        "region": "South America",
    },
    "HKG": {
        "continent": "Asia",
        "country_name": "China, Hong Kong Special Administrative Region",
        "region": "Eastern Asia",
    },
    "HMD": {
        "continent": "Oceania",
        "country_name": "Heard Island and McDonald Islands",
        "region": "Australia and New Zealand",
    },
    "HND": {
        "continent": "North America",
        "country_name": "Honduras",
        "region": "Central America",
    },
    "HRV": {
        "continent": "Europe",
        "country_name": "Croatia",
        "region": "Southern Europe",
    },
    "HTI": {
        "continent": "North America",
        "country_name": "Haiti",
        "region": "Caribbean",
    },
    "HUN": {
        "continent": "Europe",
        "country_name": "Hungary",
        "region": "Eastern Europe",
    },
    "IDN": {
        "continent": "Asia",
        "country_name": "Indonesia",
        "region": "South-eastern Asia",
    },
    "IMN": {
        "continent": "Europe",
        "country_name": "Isle of Man",
        "region": "Northern Europe",
    },
    "IND": {"continent": "Asia", "country_name": "India", "region": "Southern Asia"},
    "IOT": {
        "continent": "Africa",
        "country_name": "British Indian Ocean Territory",
        "region": "Eastern Africa",
    },
    "IRL": {
        "continent": "Europe",
        "country_name": "Ireland",
        "region": "Northern Europe",
    },
    "IRN": {"continent": "Asia", "country_name": "Iran ", "region": "Southern Asia"},
    "IRQ": {"continent": "Asia", "country_name": "Iraq", "region": "Western Asia"},
    "ISL": {
        "continent": "Europe",
        "country_name": "Iceland",
        "region": "Northern Europe",
    },
    "ISR": {"continent": "Asia", "country_name": "Israel", "region": "Western Asia"},
    "ITA": {
        "continent": "Europe",
        "country_name": "Italy",
        "region": "Southern Europe",
    },
    "JAM": {
        "continent": "North America",
        "country_name": "Jamaica",
        "region": "Caribbean",
    },
    "JEY": {
        "continent": "Europe",
        "country_name": "Jersey",
        "region": "Northern Europe",
    },
    "JOR": {"continent": "Asia", "country_name": "Jordan", "region": "Western Asia"},
    "JPN": {"continent": "Asia", "country_name": "Japan", "region": "Eastern Asia"},
    "KAZ": {
        "continent": "Asia",
        "country_name": "Kazakhstan",
        "region": "Central Asia",
    },
    "KEN": {"continent": "Africa", "country_name": "Kenya", "region": "Eastern Africa"},
    "KGZ": {
        "continent": "Asia",
        "country_name": "Kyrgyzstan",
        "region": "Central Asia",
    },
    "KHM": {
        "continent": "Asia",
        "country_name": "Cambodia",
        "region": "South-eastern Asia",
    },
    "KIR": {"continent": "Oceania", "country_name": "Kiribati", "region": "Micronesia"},
    "KNA": {
        "continent": "North America",
        "country_name": "Saint Kitts and Nevis",
        "region": "Caribbean",
    },
    "KOR": {
        "continent": "Asia",
        "country_name": "Republic of Korea",
        "region": "Eastern Asia",
    },
    "KWT": {"continent": "Asia", "country_name": "Kuwait", "region": "Western Asia"},
    "LAO": {
        "continent": "Asia",
        "country_name": "Lao People's Democratic Republic",
        "region": "South-eastern Asia",
    },
    "LBN": {"continent": "Asia", "country_name": "Lebanon", "region": "Western Asia"},
    "LBR": {
        "continent": "Africa",
        "country_name": "Liberia",
        "region": "Western Africa",
    },
    "LBY": {
        "continent": "Africa",
        "country_name": "Libya",
        "region": "Northern Africa",
    },
    "LCA": {
        "continent": "North America",
        "country_name": "Saint Lucia",
        "region": "Caribbean",
    },
    "LIE": {
        "continent": "Europe",
        "country_name": "Liechtenstein",
        "region": "Western Europe",
    },
    "LKA": {
        "continent": "Asia",
        "country_name": "Sri Lanka",
        "region": "Southern Asia",
    },
    "LSO": {
        "continent": "Africa",
        "country_name": "Lesotho",
        "region": "Southern Africa",
    },
    "LTU": {
        "continent": "Europe",
        "country_name": "Lithuania",
        "region": "Northern Europe",
    },
    "LUX": {
        "continent": "Europe",
        "country_name": "Luxembourg",
        "region": "Western Europe",
    },
    "LVA": {
        "continent": "Europe",
        "country_name": "Latvia",
        "region": "Northern Europe",
    },
    "MAC": {
        "continent": "Asia",
        "country_name": "China, Macao Special Administrative Region",
        "region": "Eastern Asia",
    },
    "MAF": {
        "continent": "North America",
        "country_name": "Saint Martin",
        "region": "Caribbean",
    },
    "MAR": {
        "continent": "Africa",
        "country_name": "Morocco",
        "region": "Northern Africa",
    },
    "MCO": {
        "continent": "Europe",
        "country_name": "Monaco",
        "region": "Western Europe",
    },
    "MDA": {
        "continent": "Europe",
        "country_name": "Republic of Moldova",
        "region": "Eastern Europe",
    },
    "MDG": {
        "continent": "Africa",
        "country_name": "Madagascar",
        "region": "Eastern Africa",
    },
    "MDV": {"continent": "Asia", "country_name": "Maldives", "region": "Southern Asia"},
    "MEX": {
        "continent": "North America",
        "country_name": "Mexico",
        "region": "Central America",
    },
    "MHL": {
        "continent": "Oceania",
        "country_name": "Marshall Islands",
        "region": "Micronesia",
    },
    "MKD": {
        "continent": "Europe",
        "country_name": "North Macedonia",
        "region": "Southern Europe",
    },
    "MLI": {"continent": "Africa", "country_name": "Mali", "region": "Western Africa"},
    "MLT": {
        "continent": "Europe",
        "country_name": "Malta",
        "region": "Southern Europe",
    },
    "MMR": {
        "continent": "Asia",
        "country_name": "Myanmar",
        "region": "South-eastern Asia",
    },
    "MNE": {
        "continent": "Europe",
        "country_name": "Montenegro",
        "region": "Southern Europe",
    },
    "MNG": {"continent": "Asia", "country_name": "Mongolia", "region": "Eastern Asia"},
    "MNP": {
        "continent": "Oceania",
        "country_name": "Northern Mariana Islands",
        "region": "Micronesia",
    },
    "MOZ": {
        "continent": "Africa",
        "country_name": "Mozambique",
        "region": "Eastern Africa",
    },
    "MRT": {
        "continent": "Africa",
        "country_name": "Mauritania",
        "region": "Western Africa",
    },
    "MSR": {
        "continent": "North America",
        "country_name": "Montserrat",
        "region": "Caribbean",
    },
    "MTQ": {
        "continent": "North America",
        "country_name": "Martinique",
        "region": "Caribbean",
    },
    "MUS": {
        "continent": "Africa",
        "country_name": "Mauritius",
        "region": "Eastern Africa",
    },
    "MWI": {
        "continent": "Africa",
        "country_name": "Malawi",
        "region": "Eastern Africa",
    },
    "MYS": {
        "continent": "Asia",
        "country_name": "Malaysia",
        "region": "South-eastern Asia",
    },
    "MYT": {
        "continent": "Africa",
        "country_name": "Mayotte",
        "region": "Eastern Africa",
    },
    "NAM": {
        "continent": "Africa",
        "country_name": "Namibia",
        "region": "Southern Africa",
    },
    "NCL": {
        "continent": "Oceania",
        "country_name": "New Caledonia",
        "region": "Melanesia",
    },
    "NER": {"continent": "Africa", "country_name": "Niger", "region": "Western Africa"},
    "NFK": {
        "continent": "Oceania",
        "country_name": "Norfolk Island",
        "region": "Australia and New Zealand",
    },
    "NGA": {
        "continent": "Africa",
        "country_name": "Nigeria",
        "region": "Western Africa",
    },
    "NIC": {
        "continent": "North America",
        "country_name": "Nicaragua",
        "region": "Central America",
    },
    "NIU": {"continent": "Oceania", "country_name": "Niue", "region": "Polynesia"},
    "NLD": {
        "continent": "Europe",
        "country_name": "Netherlands",
        "region": "Western Europe",
    },
    "NOR": {
        "continent": "Europe",
        "country_name": "Norway",
        "region": "Northern Europe",
    },
    "NPL": {"continent": "Asia", "country_name": "Nepal", "region": "Southern Asia"},
    "NRU": {"continent": "Oceania", "country_name": "Nauru", "region": "Micronesia"},
    "NZL": {
        "continent": "Oceania",
        "country_name": "New Zealand",
        "region": "Australia and New Zealand",
    },
    "OMN": {"continent": "Asia", "country_name": "Oman", "region": "Western Asia"},
    "PAK": {"continent": "Asia", "country_name": "Pakistan", "region": "Southern Asia"},
    "PAN": {
        "continent": "North America",
        "country_name": "Panama",
        "region": "Central America",
    },
    "PCN": {"continent": "Oceania", "country_name": "Pitcairn", "region": "Polynesia"},
    "PER": {
        "continent": "South America",
        "country_name": "Peru",
        "region": "South America",
    },
    "PHL": {
        "continent": "Asia",
        "country_name": "Philippines",
        "region": "South-eastern Asia",
    },
    "PLW": {"continent": "Oceania", "country_name": "Palau", "region": "Micronesia"},
    "PNG": {
        "continent": "Oceania",
        "country_name": "Papua New Guinea",
        "region": "Melanesia",
    },
    "POL": {
        "continent": "Europe",
        "country_name": "Poland",
        "region": "Eastern Europe",
    },
    "PRI": {
        "continent": "North America",
        "country_name": "Puerto Rico",
        "region": "Caribbean",
    },
    "PRK": {
        "continent": "Asia",
        "country_name": "Democratic People's Republic of Korea",
        "region": "Eastern Asia",
    },
    "PRT": {
        "continent": "Europe",
        "country_name": "Portugal",
        "region": "Southern Europe",
    },
    "PRY": {
        "continent": "South America",
        "country_name": "Paraguay",
        "region": "South America",
    },
    "PSE": {
        "continent": "Asia",
        "country_name": "State of Palestine",
        "region": "Western Asia",
    },
    "PYF": {
        "continent": "Oceania",
        "country_name": "French Polynesia",
        "region": "Polynesia",
    },
    "QAT": {"continent": "Asia", "country_name": "Qatar", "region": "Western Asia"},
    "REU": {
        "continent": "Africa",
        "country_name": "Réunion",
        "region": "Eastern Africa",
    },
    "ROU": {
        "continent": "Europe",
        "country_name": "Romania",
        "region": "Eastern Europe",
    },
    "RUS": {
        "continent": "Europe",
        "country_name": "Russian Federation",
        "region": "Eastern Europe",
    },
    "RWA": {
        "continent": "Africa",
        "country_name": "Rwanda",
        "region": "Eastern Africa",
    },
    "SAU": {
        "continent": "Asia",
        "country_name": "Saudi Arabia",
        "region": "Western Asia",
    },
    "SDN": {
        "continent": "Africa",
        "country_name": "Sudan",
        "region": "Northern Africa",
    },
    "SEN": {
        "continent": "Africa",
        "country_name": "Senegal",
        "region": "Western Africa",
    },
    "SGP": {
        "continent": "Asia",
        "country_name": "Singapore",
        "region": "South-eastern Asia",
    },
    "SGS": {
        "continent": "South America",
        "country_name": "South Georgia and the South Sandwich Islands",
        "region": "South America",
    },
    "SHN": {
        "continent": "Africa",
        "country_name": "Saint Helena",
        "region": "Western Africa",
    },
    "SJM": {
        "continent": "Europe",
        "country_name": "Svalbard and Jan Mayen Islands",
        "region": "Northern Europe",
    },
    "SLB": {
        "continent": "Oceania",
        "country_name": "Solomon Islands",
        "region": "Melanesia",
    },
    "SLE": {
        "continent": "Africa",
        "country_name": "Sierra Leone",
        "region": "Western Africa",
    },
    "SLV": {
        "continent": "North America",
        "country_name": "El Salvador",
        "region": "Central America",
    },
    "SMR": {
        "continent": "Europe",
        "country_name": "San Marino",
        "region": "Southern Europe",
    },
    "SOM": {
        "continent": "Africa",
        "country_name": "Somalia",
        "region": "Eastern Africa",
    },
    "SPM": {
        "continent": "North America",
        "country_name": "Saint Pierre and Miquelon",
        "region": "Northern America",
    },
    "SRB": {
        "continent": "Europe",
        "country_name": "Serbia",
        "region": "Southern Europe",
    },
    "SSD": {
        "continent": "Africa",
        "country_name": "South Sudan",
        "region": "Eastern Africa",
    },
    "STP": {
        "continent": "Africa",
        "country_name": "Sao Tome and Principe",
        "region": "Middle Africa",
    },
    "SUR": {
        "continent": "South America",
        "country_name": "Suriname",
        "region": "South America",
    },
    "SVK": {
        "continent": "Europe",
        "country_name": "Slovakia",
        "region": "Eastern Europe",
    },
    "SVN": {
        "continent": "Europe",
        "country_name": "Slovenia",
        "region": "Southern Europe",
    },
    "SWE": {
        "continent": "Europe",
        "country_name": "Sweden",
        "region": "Northern Europe",
    },
    "SWZ": {
        "continent": "Africa",
        "country_name": "Eswatini",
        "region": "Southern Africa",
    },
    "SXM": {
        "continent": "North America",
        "country_name": "Sint Maarten",
        "region": "Caribbean",
    },
    "SYC": {
        "continent": "Africa",
        "country_name": "Seychelles",
        "region": "Eastern Africa",
    },
    "SYR": {
        "continent": "Asia",
        "country_name": "Syrian Arab Republic",
        "region": "Western Asia",
    },
    "TCA": {
        "continent": "North America",
        "country_name": "Turks and Caicos Islands",
        "region": "Caribbean",
    },
    "TCD": {"continent": "Africa", "country_name": "Chad", "region": "Middle Africa"},
    "TGO": {"continent": "Africa", "country_name": "Togo", "region": "Western Africa"},
    "THA": {
        "continent": "Asia",
        "country_name": "Thailand",
        "region": "South-eastern Asia",
    },
    "TJK": {
        "continent": "Asia",
        "country_name": "Tajikistan",
        "region": "Central Asia",
    },
    "TKL": {"continent": "Oceania", "country_name": "Tokelau", "region": "Polynesia"},
    "TKM": {
        "continent": "Asia",
        "country_name": "Turkmenistan",
        "region": "Central Asia",
    },
    "TLS": {
        "continent": "Asia",
        "country_name": "Timor-Leste",
        "region": "South-eastern Asia",
    },
    "TON": {"continent": "Oceania", "country_name": "Tonga", "region": "Polynesia"},
    "TTO": {
        "continent": "North America",
        "country_name": "Trinidad and Tobago",
        "region": "Caribbean",
    },
    "TUN": {
        "continent": "Africa",
        "country_name": "Tunisia",
        "region": "Northern Africa",
    },
    "TUR": {"continent": "Asia", "country_name": "Turkey", "region": "Western Asia"},
    "TUV": {"continent": "Oceania", "country_name": "Tuvalu", "region": "Polynesia"},
    "TZA": {
        "continent": "Africa",
        "country_name": "United Republic of Tanzania",
        "region": "Eastern Africa",
    },
    "UGA": {
        "continent": "Africa",
        "country_name": "Uganda",
        "region": "Eastern Africa",
    },
    "UKR": {
        "continent": "Europe",
        "country_name": "Ukraine",
        "region": "Eastern Europe",
    },
    "UMI": {
        "continent": "Oceania",
        "country_name": "United States Minor Outlying Islands",
        "region": "Micronesia",
    },
    "URY": {
        "continent": "South America",
        "country_name": "Uruguay",
        "region": "South America",
    },
    "USA": {
        "continent": "North America",
        "country_name": "United States of America",
        "region": "Northern America",
    },
    "UZB": {
        "continent": "Asia",
        "country_name": "Uzbekistan",
        "region": "Central Asia",
    },
    "VAT": {
        "continent": "Europe",
        "country_name": "Holy See",
        "region": "Southern Europe",
    },
    "VCT": {
        "continent": "North America",
        "country_name": "Saint Vincent and the Grenadines",
        "region": "Caribbean",
    },
    "VEN": {
        "continent": "South America",
        "country_name": "Venezuela ",
        "region": "South America",
    },
    "VGB": {
        "continent": "North America",
        "country_name": "British Virgin Islands",
        "region": "Caribbean",
    },
    "VIR": {
        "continent": "North America",
        "country_name": "United States Virgin Islands",
        "region": "Caribbean",
    },
    "VNM": {
        "continent": "Asia",
        "country_name": "Viet Nam",
        "region": "South-eastern Asia",
    },
    "VUT": {"continent": "Oceania", "country_name": "Vanuatu", "region": "Melanesia"},
    "WLF": {
        "continent": "Oceania",
        "country_name": "Wallis and Futuna Islands",
        "region": "Polynesia",
    },
    "WSM": {"continent": "Oceania", "country_name": "Samoa", "region": "Polynesia"},
    "YEM": {"continent": "Asia", "country_name": "Yemen", "region": "Western Asia"},
    "ZAF": {
        "continent": "Africa",
        "country_name": "South Africa",
        "region": "Southern Africa",
    },
    "ZMB": {
        "continent": "Africa",
        "country_name": "Zambia",
        "region": "Eastern Africa",
    },
    "ZWE": {
        "continent": "Africa",
        "country_name": "Zimbabwe",
        "region": "Eastern Africa",
    },
}
